#!/bin/bash

echo 'Generating default (English) page...'
php -d short_open_tag=On src/index.php en > index.html

echo 'Generating Chinese page...'
php -d short_open_tag=On src/index.php zh > zh/index.html

echo 'Generating Korian page...'
php -d short_open_tag=On src/index.php ko > ko/index.html

echo 'Generating Russian page...'
php -d short_open_tag=On src/index.php ru > ru/index.html

echo 'Generating Japanese page...'
php -d short_open_tag=On src/index.php jp > jp/index.html

echo 'Generating Spanish page...'
php -d short_open_tag=On src/index.php es > es/index.html

echo 'Generating Italian page...'
php -d short_open_tag=On src/index.php it > it/index.html

echo 'Generating Portugal page...'
php -d short_open_tag=On src/index.php pt > pt/index.html

echo 'Generating Hindi page...'
php -d short_open_tag=On src/index.php hi > hi/index.html

echo 'Generating Filipino page...'
php -d short_open_tag=On src/index.php ph > ph/index.html

echo 'Generating Nederlands page...'
php -d short_open_tag=On src/index.php nl > nl/index.html

echo 'Generating Arabic page...'
php -d short_open_tag=On src/index.php ar > ar/index.html

echo 'Done.'
