#!/bin/bash

echo 'Generating default (english) page...'
php src/index.php en > index.new.html

echo 'Generating chinese page...'
php src/index.php zh > zh/index.new.html

echo 'Generating korian page...'
php src/index.php ko > ko/index.new.html

echo 'Generating russian page...'
php src/index.php ru > ru/index.new.html

echo 'Generating japanese page...'
php src/index.php jp > jp/index.html

echo 'Done.'
